# The values in this file are just examples, they won't actually work

reddit:
  # see http://praw.readthedocs.io/en/latest/getting_started/quick_start.html
  my_user_agent: 'android:com.example.myredditapp:v1.2.3 (by /u/kemitche)'
  my_client_id: 'bunch-o-code'
  my_client_secret: 'bunch-o-code_longer'
  my_username: 'somebot123'
  my_password: 'hunter123'

twitter:
  # see https://twython.readthedocs.io/en/latest/
  app_key: 'load-o-code'
  app_key_secret: 'load-o-code_longer'
  access_token: 'load-o-code_longer_still'
  access_token_secret: 'load-o-code_longest_yet'
  tweet_length: 120 # max 140, shorter sometimes works better

age:
  corpus_age_limit_days: 120
  checked_logs_age_limit_days: 10

media:
  max_jpg_store: 10

subreddits:
  - 'list'
  - 'of'
  - 'subreddits'
  - 'to'
  - 'access'